import { describe, expect, it } from 'vitest';

import {
  formatAsYouType,
  formatNational,
  isValidNationalNumber,
  nationalNumber,
  toE164,
  type PhoneRules,
} from '@/core/country-service/country-service.phone';

// libphonenumber's own answers for sample numbers of every country, and the rules the
// address-rules service serves for them. Generated by `scripts/phone.py` in i18n-rules-v2
// (`test/fixtures/phone-corpus.json` there): regenerate it there and copy it here.
import corpus from './fixtures/phone-corpus.json';

interface Sample {
  type: string;
  typed: string;
  national?: string;
  e164?: string;
  valid: boolean;
  /** libphonenumber's as-you-type output after each digit of `typed`. */
  asYouType: string[];
}

const countries = Object.entries(
  corpus.countries as Record<string, { rules: PhoneRules; samples: Sample[] }>
);

const each = (
  check: (code: string, rules: PhoneRules, sample: Sample) => string | null
): string[] =>
  countries.flatMap(([code, { rules, samples }]) =>
    samples
      .map(sample => check(code, rules, sample))
      .filter((problem): problem is string => problem !== null)
  );

describe('country-service.phone, against libphonenumber for every country', () => {
  it('covers every country with phone data', () => {
    expect(countries.length).toBe(242);
  });

  it('judges every sample number valid or not as libphonenumber does', () => {
    const disagreements = each((code, rules, sample) =>
      isValidNationalNumber(nationalNumber(sample.typed, rules), rules) === sample.valid
        ? null
        : `${code} ${sample.type} ${sample.typed}`
    );
    expect(disagreements).toEqual([]);
  });

  it('builds the E.164 value libphonenumber builds', () => {
    const wrong = each((code, rules, sample) =>
      !sample.e164 || toE164(sample.typed, rules) === sample.e164
        ? null
        : `${code} ${sample.typed} → ${toE164(sample.typed, rules)}, not ${sample.e164}`
    );
    expect(wrong).toEqual([]);
  });

  it('writes a whole number the way libphonenumber writes it nationally', () => {
    const wrong = each((code, rules, sample) => {
      if (!sample.national) return null;
      const written = formatNational(nationalNumber(sample.typed, rules), rules);
      return written === sample.national
        ? null
        : `${code} ${sample.type}: ${written}, not ${sample.national}`;
    });
    expect(wrong).toEqual([]);
  });

  it('ends on the national form when the number is typed one digit at a time', () => {
    const wrong = each((code, rules, sample) => {
      if (!sample.national) return null;
      // As the phone field does it: it keeps the digits and shows what the formatter makes.
      let typed = '';
      let field = '';
      for (const digit of sample.typed.replace(/\D/g, '')) {
        typed += digit;
        field = formatAsYouType(typed, rules);
      }
      return field === sample.national ? null : `${code}: ${field}, not ${sample.national}`;
    });
    expect(wrong).toEqual([]);
  });

  /**
   * A ratchet, not a contract: every whole number above ends on libphonenumber's national
   * form, but on the way there this module picks a format by simpler rules than
   * libphonenumber's as-you-type formatter (Afghanistan's `0701` shows as `0 701`, not
   * `070 1`). Raise the floor when that gap closes; never lower it.
   */
  it('shows what libphonenumber shows at no fewer keystrokes than before', () => {
    let matching = 0;
    for (const [, { rules, samples }] of countries) {
      for (const sample of samples) {
        const digits = sample.typed.replace(/\D/g, '');
        sample.asYouType.forEach((expected, i) => {
          if (formatAsYouType(digits.slice(0, i + 1), rules) === expected) matching++;
        });
      }
    }
    expect(matching).toBeGreaterThanOrEqual(14062);
  });

  it('never drops a digit the shopper typed while the number is incomplete', () => {
    const lost = each((code, rules, sample) => {
      const digits = sample.typed.replace(/\D/g, '');
      for (let end = 1; end < digits.length; end++) {
        const typed = digits.slice(0, end);
        const shown = formatAsYouType(typed, rules).replace(/\D/g, '');
        // A format may add digits of its own (Argentina's mobile `15`), never remove one.
        let at = 0;
        for (const digit of shown) if (digit === typed[at]) at++;
        if (at < typed.length) return `${code}: ${typed} shown as ${formatAsYouType(typed, rules)}`;
      }
      return null;
    });
    expect(lost).toEqual([]);
  });
});

describe('country-service.phone, by example', () => {
  const rules = (code: string): PhoneRules =>
    (corpus.countries as Record<string, { rules: PhoneRules }>)[code].rules;

  it('groups a US number as it is typed', () => {
    expect(formatAsYouType('415', rules('US'))).toBe('415');
    // libphonenumber's own as-you-type formatter shows this too: seven digits is a local
    // US number, so the area code only gets its brackets at the eighth.
    expect(formatAsYouType('41555', rules('US'))).toBe('415-55');
    expect(formatAsYouType('41555526', rules('US'))).toBe('(415) 555-26');
    expect(formatAsYouType('4155552671', rules('US'))).toBe('(415) 555-2671');
  });

  it('keeps the national prefix a shopper types, and drops it from E.164', () => {
    expect(formatAsYouType('0812345678', rules('TH'))).toBe('081 234 5678');
    expect(toE164('081 234 5678', rules('TH'))).toBe('+66812345678');
  });

  it("keeps Italy's leading zero, which is part of the number", () => {
    expect(toE164('02 1234 5678', rules('IT'))).toBe('+390212345678');
  });

  it('refuses a UK mobile one digit short', () => {
    expect(isValidNationalNumber(nationalNumber('07400 12345', rules('GB')), rules('GB'))).toBe(
      false
    );
  });
});
